# Generated by Django 3.0.6 on 2020-05-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tourn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='user',
            new_name='user2',
        ),
        migrations.AddField(
            model_name='game',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1', to='Tourn.User'),
            preserve_default=False,
        ),
    ]
