# Generated by Django 3.0.6 on 2020-05-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourn', '0003_auto_20200523_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='score1',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='score2',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
