# Generated by Django 3.0.6 on 2020-05-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourn', '0006_auto_20200529_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
