# Generated by Django 3.0.6 on 2020-06-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourn', '0008_auto_20200602_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image_src',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('tournament', 'license', 'rank')},
        ),
    ]
