# Generated by Django 3.0.6 on 2020-06-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourn', '0010_auto_20200607_1909'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('tournament', 'matchno')},
        ),
    ]
